spring:
  application:
    name: sell-config
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/Guiee/spring-cloud-config-repo.git
          # Git仓库账号
          username: Guiee
          # Git仓库密码
          password: 12345wyg/.