spring:
  application:
    name: eureka-cluster
  profiles:
    active: peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/,http://peer3:8763/eureka/
    register-with-eureka: false
# 修改configrations  VM options -> -Dserver.port=8761
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3